version: '3'
services:    
  mysql:
    image: mysql:5.7.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ssalesioproapp2018
      - MYSQL_USER=proapp5cs2018
      - MYSQL_PASSWORD=''
    volumes:
      - mysql-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8.0
    restart: always
    ports:
      - 8080:8080
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=ssalesioproapp2018
      - PMA_USER=proapp5cs2018
      - PMA_PASSWORD=''
    volumes:
      - session-data:/sessions

volumes:
  mysql-data:
    driver: 'local'
  session-data:
    driver: 'local'